### PR TITLE
Feature: Multi-language support

### PR DESCRIPTION
**Pull request by chaaya**
## Feature
- Native out of the box support for English(default) and Swedish.
- Can be configured via the dashboardProvider.
- Translations/langauges can be added to the framework.

## Why?
It can seem to be little bit tacky when a system doesnt uses English, in my case our system is in Swedish and all adf labels/tooltips are in English. I think the language support takes the framework to the next level. 

Hope you like it :)

### CODE REVIEW

**Comment by sdorra** [comment]
Looks really nice. Great job. I would love to see it in the next version.

But i'm not sure if i like the name "culture", i think i would feel more comfortable with a name like i18n, locale, l10n or something like this. Is there a special reason for culture?

Do we need a new module or could we add it to adf.provider, to reduce complexity?

**Comment by sdorra** [comment]
This would fix #102

**Comment by sdorra** [comment]
The documentation should be placed elsewhere in the wiki, extra file or we could add some extra pages to the api documentation. But i think the readme would get too long.

**Comment by chaaya** [comment]
I had a hard time deciding the name to be honest :) I have used kendo alot and they are using culture, but a culture also has an affect on dateformats and stuff, so it may be the wrong module name to use.

adf.locale is good module name. 

```javascript
dashboardProvider.setLocale('en-US')
```

I think it should be a own module, since it has a very narrow scope. That helps with the unit testing if we where to extend the locacle module with its own provider and translation factory that we later could inject into the dashboardProvider.
Maybe I could fix that in the future, but this works for now. 

Sound good?

**Comment by sdorra** [comment]
Yes, sounds good for me.

**Comment by sdorra** [comment]
Thank you very much.

**Comment by chaaya** [comment]
@sdorra thank u :) would love som help regarding the wiki. Maybe we can take that privately over gitter?

**Pull request merged**
