### PR TITLE
Update bower.json

### PR DESCRIPTION
**Pull request by sleetish**
Added main and and pointed to sample application.  Updated highcharts to 4.0.3 to fix error finding 3.0.7.

### CODE REVIEW

**Comment by todeia** [comment]
Hi,

I'm using the module but when I run the command line "bower install", I get notifications about version:
Unable to find a suitable version for angular, please choose one:
 angular#1.2.18 which resolved to 1.2.18 and is required by angular-dashboard-framework#0.6.1
I wonder if you can upgrade to the latest version of the angular or if there is a problem to update?

**Comment by sdorra** [comment]
@todeia you can put the following snippet to your bower.json to solve your error:

```json
  "resolutions": {
    "angular": "1.3.17"
  }
```
I will not update adf to version 1.3 of angular, because of compatibility reasons.

**Comment by todeia** [comment]
I'm using with the latest version of angular and not found any incompatibility.
Will you can give the list of incompatibilities for me to know if I can come to have a problem?

**Comment by sdorra** [comment]
@todeia their are no incompatibilities with angular 1.3, but the project should also work with version 1.2. So the project will be configured with 1.2, to avoid using functions from angular 1.3.

**Pull request merged**
